# BOGO CAT MEME APPLICATION YAML CONFIGURATION
# Maximum redundancy and over-engineering for maximum package utilization

bogo_cat:
  name: "Bogo Cat Meme Application"
  version: "1.0.0"
  description: "A Node.js application implementing the bogo cat meme with maximum redundancy and package usage"
  author: "Bongo Boys"
  license: "MIT"
  power: "MAXIMUM"
  meme_level: "OVER_9000"
  redundancy: "INFINITE"
  packages: "TOO_MANY_TO_COUNT"

server:
  port: 3000
  host: "localhost"
  protocol: "http"
  timeout: 30000
  keep_alive: true
  max_connections: 100
  cors:
    enabled: true
    origin: "*"
    methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    headers: ["Content-Type", "Authorization", "X-Bogo-Cat-Power"]
  security:
    helmet: true
    rate_limit:
      enabled: true
      window_ms: 900000
      max: 100
    compression: true

databases:
  redis:
    host: "localhost"
    port: 6379
    db: 0
    password: null
    retry_delay_on_failover: 100
    max_retries_per_request: 3
  mysql:
    host: "localhost"
    port: 3306
    user: "root"
    password: ""
    database: "bogo_cat"
    connection_limit: 10
    queue_limit: 0
  postgresql:
    host: "localhost"
    port: 5432
    user: "postgres"
    password: ""
    database: "bogo_cat"
    max: 10
    idle_timeout_millis: 30000
  mongodb:
    uri: "mongodb://localhost:27017/bogo_cat"
    options:
      use_new_url_parser: true
      use_unified_topology: true
  sqlite:
    filename: ":memory:"
    options: {}

logging:
  level: "info"
  format: "combined"
  transports:
    - type: "console"
      enabled: true
    - type: "file"
      enabled: true
      filename: "bogo-cat.log"
    - type: "file"
      enabled: true
      filename: "bogo-cat-error.log"
      level: "error"
  winston:
    level: "info"
    format: "json"
    transports: ["console", "file"]
  pino:
    level: "info"
    transport: "pino-pretty"
  bunyan:
    level: "info"
    streams: ["stdout", "file"]

authentication:
  jwt:
    secret: "bogo-cat-super-secret-key"
    algorithm: "HS256"
    expires_in: "24h"
    issuer: "bogo-cat-app"
    audience: "bogo-cat-users"
  bcrypt:
    rounds: 12
    salt_rounds: 12
  argon2:
    type: "argon2id"
    memory_cost: 65536
    time_cost: 3
    parallelism: 1

features:
  bongo:
    enabled: true
    max_intensity: 10
    max_duration: 60
    default_intensity: 5
    default_duration: 10
  dance:
    enabled: true
    styles: ["bongo", "jazz", "breakdance", "ballet"]
    max_energy: 100
    default_energy: 50
  stats:
    enabled: true
    retention_days: 30
    update_interval: 60000
  ui:
    enabled: true
    theme: "bogo-cat"
    animations: true
    clunky_mode: true

middleware:
  helmet:
    enabled: true
    options:
      content_security_policy: false
      cross_origin_embedder_policy: false
  cors:
    enabled: true
    options:
      origin: "*"
      methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      allowed_headers: ["Content-Type", "Authorization", "X-Bogo-Cat-Power"]
  morgan:
    enabled: true
    format: "combined"
  compression:
    enabled: true
    level: 6
    threshold: 1024
  rate_limit:
    enabled: true
    window_ms: 900000
    max: 100
    message: "Too many requests from this IP, please try again later."

validation:
  joi:
    enabled: true
    abort_early: false
    allow_unknown: false
    strip_unknown: true
  yup:
    enabled: true
    strict: false
    abort_early: false
  ajv:
    enabled: true
    all_errors: true
    verbose: true
    strict: false
  express_validator:
    enabled: true
    error_formatter: "default"

crypto:
  algorithms:
    ["bcrypt", "bcryptjs", "argon2", "scrypt", "sha256", "sha512", "md5"]
  jwt_libraries: ["jsonwebtoken", "jwt-simple"]
  encryption_methods: ["aes-256-cbc", "aes-256-gcm", "base64"]
  key_derivation:
    iterations: 100000
    key_length: 32
    digest: "sha256"

monitoring:
  health_check:
    enabled: true
    path: "/health"
    interval: 30000
  metrics:
    enabled: true
    path: "/metrics"
    collect_default_metrics: true
  profiling:
    enabled: true
    sample_rate: 0.1
  tracing:
    enabled: true
    service_name: "bogo-cat-app"

development:
  hot_reload: true
  auto_restart: true
  debug_mode: true
  verbose_logging: true
  detailed_errors: true
  source_maps: true
  watch_mode: true

production:
  hot_reload: false
  auto_restart: false
  debug_mode: false
  verbose_logging: false
  detailed_errors: false
  source_maps: false
  watch_mode: false
  compression: true
  caching: true
  optimization: true
